using Accountrack.SharedKernel.Pdf;
using Accountrack.Web.Common.Pdf;
using FluentAssertions;
using Xunit;

namespace Accountrack.BuildingBlocks.UnitTests;

public class PdfRendererTests
{
    static PdfRendererTests() => QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;

    private static PdfDocument Sample() => new(
        "Invoice", "SI/202606/00001",
        new PdfParty("Shirt Lab", new[] { "PT Shirt Lab Indonesia", "NPWP: 01.234.567.8-901.000" }),
        "Bill To",
        new PdfParty("Acme Corp", System.Array.Empty<string>()),
        new[] { new PdfField("Invoice date", "2026-06-20"), new PdfField("Due date", "2026-07-20") },
        new[]
        {
            new PdfLineItem("Widget", "10", "IDR 5,000", "11%", "IDR 50,000"),
            new PdfLineItem("Gadget", "2", "IDR 100,000", "11%", "IDR 200,000"),
        },
        new[]
        {
            new PdfTotalLine("Subtotal", "IDR 250,000"),
            new PdfTotalLine("VAT (PPN)", "IDR 27,500"),
            new PdfTotalLine("Total", "IDR 277,500", Emphasis: true),
        },
        "Thank you for your business.",
        "Shirt Lab · Generated by Accountrack");

    [Fact]
    public void Renders_a_valid_pdf()
    {
        var bytes = PdfRenderer.Render(Sample());

        bytes.Should().NotBeEmpty();
        // PDF files start with the "%PDF" magic header.
        System.Text.Encoding.ASCII.GetString(bytes, 0, 4).Should().Be("%PDF");
    }

    [Fact]
    public void Embeds_the_brand_font()
    {
        // QuestPDF subsets and embeds registered fonts; the font descriptor keeps the face name
        // (e.g. "ABCDEF+PlusJakartaSans-Regular"), so a valid embed leaves "PlusJakartaSans" in the bytes.
        var latin1 = System.Text.Encoding.Latin1.GetString(PdfRenderer.Render(Sample()));

        latin1.Should().Contain("PlusJakartaSans", "the brand typeface must be embedded in the PDF");
    }
}
