using System.Globalization;
using Accountrack.Application.Abstractions.Context;
using Accountrack.Application.Abstractions.Messaging;
using Accountrack.Modules.Contracts.Company;
using Accountrack.Modules.Contracts.MasterData;
using Accountrack.Purchasing.Application.Abstractions;
using Accountrack.Purchasing.Domain;
using Accountrack.SharedKernel.Pdf;
using Accountrack.SharedKernel.Results;

namespace Accountrack.Purchasing.Application.Features;

internal static class PurchasingPdfFormat
{
    private static readonly CultureInfo Id = new("id-ID");

    public static string Money(decimal value, string currency) => $"{currency} {value.ToString("N0", Id)}";
    public static string Qty(decimal value) => value.ToString("0.####", CultureInfo.InvariantCulture);
    public static string Pct(decimal rate) => (rate * 100m).ToString("0.##", CultureInfo.InvariantCulture) + "%";

    public static PdfParty Company(CompanyInfo? c)
    {
        if (c is null) return new PdfParty("Accountrack", System.Array.Empty<string>());
        var lines = new List<string>();
        if (!string.IsNullOrWhiteSpace(c.LegalName) && c.LegalName != c.Name) lines.Add(c.LegalName!);
        if (!string.IsNullOrWhiteSpace(c.TaxId)) lines.Add($"NPWP: {c.TaxId}");
        return new PdfParty(string.IsNullOrWhiteSpace(c.Name) ? c.Code : c.Name, lines);
    }

    public static string Footer(CompanyInfo? c) =>
        $"{(c is null || string.IsNullOrWhiteSpace(c.Name) ? "Accountrack" : c.Name)} · Generated by Accountrack";
}

// --- Purchase order PDF (we are the buyer; sent to the supplier) ---

public sealed record GetPurchaseOrderPdfQuery(Guid Id) : IQuery<PdfDocument>;

public sealed class GetPurchaseOrderPdfHandler : IQueryHandler<GetPurchaseOrderPdfQuery, PdfDocument>
{
    private readonly IPurchaseOrderRepository _orders;
    private readonly IMasterDataLookup _lookup;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;

    public GetPurchaseOrderPdfHandler(
        IPurchaseOrderRepository orders, IMasterDataLookup lookup, ICompanyDirectory companies, ITenantContext tenant)
    { _orders = orders; _lookup = lookup; _companies = companies; _tenant = tenant; }

    public async Task<Result<PdfDocument>> Handle(GetPurchaseOrderPdfQuery request, CancellationToken ct)
    {
        var order = await _orders.GetByIdAsync(request.Id, ct);
        if (order is null) return PurchasingErrors.NotFound;

        var company = await _companies.GetAsync(_tenant.CompanyId, ct);
        var names = await _lookup.ResolveNamesAsync(
            order.Lines.Select(l => l.ProductId).Append(order.SupplierId).Distinct().ToArray(), ct);
        var cur = order.Currency;

        var lines = order.Lines.Select(l => new PdfLineItem(
            names.GetValueOrDefault(l.ProductId, l.ProductId.ToString()),
            PurchasingPdfFormat.Qty(l.Quantity),
            PurchasingPdfFormat.Money(l.UnitPrice, cur),
            PurchasingPdfFormat.Pct(l.TaxRate),
            PurchasingPdfFormat.Money(l.LineTotal, cur))).ToList();

        var totals = new List<PdfTotalLine> { new("Subtotal", PurchasingPdfFormat.Money(order.SubTotal, cur)) };
        if (order.TaxTotal != 0m) totals.Add(new("VAT (PPN)", PurchasingPdfFormat.Money(order.TaxTotal, cur)));
        totals.Add(new("Total", PurchasingPdfFormat.Money(order.GrandTotal, cur), Emphasis: true));

        return new PdfDocument(
            "Purchase Order", order.Number,
            PurchasingPdfFormat.Company(company),
            "Supplier",
            new PdfParty(names.GetValueOrDefault(order.SupplierId, order.SupplierId.ToString()), System.Array.Empty<string>()),
            new[] { new PdfField("Order date", order.OrderDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)) },
            lines, totals, order.Notes, PurchasingPdfFormat.Footer(company));
    }
}

// --- Purchase invoice (bill) PDF — internal record; from the supplier, billed to us ---

public sealed record GetPurchaseInvoicePdfQuery(Guid Id) : IQuery<PdfDocument>;

public sealed class GetPurchaseInvoicePdfHandler : IQueryHandler<GetPurchaseInvoicePdfQuery, PdfDocument>
{
    private readonly IPurchaseInvoiceRepository _invoices;
    private readonly IMasterDataLookup _lookup;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;

    public GetPurchaseInvoicePdfHandler(
        IPurchaseInvoiceRepository invoices, IMasterDataLookup lookup, ICompanyDirectory companies, ITenantContext tenant)
    { _invoices = invoices; _lookup = lookup; _companies = companies; _tenant = tenant; }

    public async Task<Result<PdfDocument>> Handle(GetPurchaseInvoicePdfQuery request, CancellationToken ct)
    {
        var invoice = await _invoices.GetByIdAsync(request.Id, ct);
        if (invoice is null) return Error.NotFound("PURCHASING.PI_NOT_FOUND", "Purchase invoice not found.");

        var company = await _companies.GetAsync(_tenant.CompanyId, ct);
        var names = await _lookup.ResolveNamesAsync(
            invoice.Lines.Select(l => l.ProductId).Append(invoice.SupplierId).Distinct().ToArray(), ct);
        var cur = invoice.Currency;

        var lines = invoice.Lines.Select(l => new PdfLineItem(
            names.GetValueOrDefault(l.ProductId, l.ProductId.ToString()),
            PurchasingPdfFormat.Qty(l.Quantity),
            PurchasingPdfFormat.Money(l.UnitPrice, cur),
            PurchasingPdfFormat.Pct(l.TaxRate),
            PurchasingPdfFormat.Money(l.LineTotal, cur))).ToList();

        var totals = new List<PdfTotalLine> { new("Subtotal", PurchasingPdfFormat.Money(invoice.SubTotal, cur)) };
        if (invoice.TaxTotal != 0m) totals.Add(new("VAT (PPN)", PurchasingPdfFormat.Money(invoice.TaxTotal, cur)));
        totals.Add(new("Total", PurchasingPdfFormat.Money(invoice.GrandTotal, cur), Emphasis: true));

        var meta = new List<PdfField>
        {
            new("Invoice date", invoice.InvoiceDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
            new("Due date", invoice.DueDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
        };
        if (!string.IsNullOrWhiteSpace(invoice.SupplierInvoiceNo))
        {
            meta.Add(new PdfField("Supplier ref", invoice.SupplierInvoiceNo!));
        }

        return new PdfDocument(
            "Purchase Invoice", invoice.Number,
            new PdfParty(names.GetValueOrDefault(invoice.SupplierId, invoice.SupplierId.ToString()), System.Array.Empty<string>()),
            "Bill To",
            PurchasingPdfFormat.Company(company),
            meta, lines, totals, invoice.Notes, PurchasingPdfFormat.Footer(company));
    }
}
