using System.Reflection;
using Accountrack.Application.Abstractions.Context;
using Accountrack.Infrastructure.Common.Transactions;
using Accountrack.SharedKernel.Auditing;
using Accountrack.SharedKernel.Domain;
using Microsoft.EntityFrameworkCore;

namespace Accountrack.Infrastructure.Common.Persistence;

/// <summary>
/// Base <see cref="DbContext"/> for every module. Applies the cross-cutting conventions that
/// make the platform safe by default (docs/DATABASE.md, MULTI_TENANCY.md):
///   - a global query filter excluding soft-deleted rows on every <see cref="Entity"/>;
///   - an additional tenant + company filter on every <see cref="TenantOwnedEntity"/>;
///   - a provider-agnostic optimistic-concurrency token on every entity;
///   - ignoring the in-memory domain-event buffer.
/// Derived module contexts call <see cref="ApplyAccountrackConventions"/> from OnModelCreating.
/// </summary>
public abstract class BaseDbContext : DbContext, ITransactionalDbContext
{
    private readonly ITenantContext _tenant;

    protected BaseDbContext(DbContextOptions options, ITenantContext tenant) : base(options) =>
        _tenant = tenant;

    /// <summary>Exposed so the compiled global query filters resolve the tenant per query.</summary>
    public Guid CurrentTenantId => _tenant.TenantId;

    public Guid CurrentCompanyId => _tenant.CompanyId;

    /// <summary>Lets the cross-module unit of work enlist and persist this context (ADR-0007).</summary>
    public DbContext DbContext => this;

    /// <summary>
    /// Translates EF Core's optimistic-concurrency failure into a provider-agnostic
    /// <see cref="ConcurrencyConflictException"/> (ADR-0021) so callers and the web layer can react to
    /// a stale write without depending on EF. Raised when a tracked row's rowversion no longer matches.
    /// </summary>
    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            return await base.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateConcurrencyException ex)
        {
            throw new ConcurrencyConflictException(
                "The record was modified or removed by someone else since it was loaded.", ex);
        }
    }

    protected void ApplyAccountrackConventions(ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            var clr = entityType.ClrType;

            if (!typeof(Entity).IsAssignableFrom(clr))
            {
                continue;
            }

            // The in-memory event buffer is not persisted.
            modelBuilder.Entity(clr).Ignore(nameof(Entity.DomainEvents));

            // GUIDs are generated by the domain (ADR-0005), not the store. Telling EF this makes it
            // correctly mark newly-constructed children of a *loaded* aggregate as Added (insert)
            // rather than mis-detecting the pre-set key as an existing row to update.
            modelBuilder.Entity(clr).Property(nameof(Entity.Id)).ValueGeneratedNever();

            // Optimistic concurrency token (ADR-0021). Provider-agnostic: unlike SQL Server's
            // store-generated `rowversion`, PostgreSQL has no equivalent, so the token is a plain
            // `bytea` concurrency token whose value is bumped by AuditingSaveChangesInterceptor on
            // every insert/update. EF still emits it in the UPDATE ... WHERE clause for the check.
            modelBuilder.Entity(clr).Property(nameof(Entity.RowVersion))
                .IsConcurrencyToken()
                .ValueGeneratedNever();

            // Global query filters (most specific first).
            if (typeof(TenantOwnedEntity).IsAssignableFrom(clr))
            {
                InvokeGeneric(nameof(ApplyTenantOwnedFilter), clr, modelBuilder);
            }
            else if (typeof(TenantScopedEntity).IsAssignableFrom(clr))
            {
                InvokeGeneric(nameof(ApplyTenantScopedFilter), clr, modelBuilder);
            }
            else
            {
                InvokeGeneric(nameof(ApplySoftDeleteFilter), clr, modelBuilder);
            }
        }

        // Every context can write audit entries into the shared audit table, but only the
        // AuditLog module's context owns its migration (ADR-0026).
        MapAuditEntry(modelBuilder, excludeFromMigrations: true);
    }

    /// <summary>The shared, append-only audit table (ADR-0006/0026).</summary>
    public const string AuditSchema = "audit";
    public const string AuditTable = "AuditEntries";

    /// <summary>
    /// Maps <see cref="AuditEntry"/> to the shared audit table. Participating module contexts
    /// exclude it from their migrations; the AuditLog context includes it (owns creation).
    /// </summary>
    public static void MapAuditEntry(ModelBuilder modelBuilder, bool excludeFromMigrations)
    {
        modelBuilder.Entity<AuditEntry>(b =>
        {
            b.ToTable(AuditTable, AuditSchema, t =>
            {
                if (excludeFromMigrations)
                {
                    t.ExcludeFromMigrations();
                }
            });
            b.HasKey(e => e.Id);
            b.Property(e => e.EntityType).IsRequired().HasMaxLength(200);
            b.Property(e => e.EntityId).IsRequired().HasMaxLength(128);
            b.Property(e => e.Action).HasConversion<int>();
            b.Property(e => e.ChangesJson).IsRequired();
            b.Property(e => e.CorrelationId).HasMaxLength(128);
            b.HasIndex(e => new { e.TenantId, e.EntityType, e.EntityId });
            b.HasIndex(e => e.TimestampUtc);
        });
    }

    private void InvokeGeneric(string methodName, Type clrType, ModelBuilder modelBuilder)
    {
        typeof(BaseDbContext)
            .GetMethod(methodName, BindingFlags.Instance | BindingFlags.NonPublic)!
            .MakeGenericMethod(clrType)
            .Invoke(this, new object[] { modelBuilder });
    }

    private void ApplySoftDeleteFilter<TEntity>(ModelBuilder modelBuilder)
        where TEntity : Entity
    {
        modelBuilder.Entity<TEntity>().HasQueryFilter(e => !e.IsDeleted);
    }

    private void ApplyTenantScopedFilter<TEntity>(ModelBuilder modelBuilder)
        where TEntity : TenantScopedEntity
    {
        modelBuilder.Entity<TEntity>().HasQueryFilter(e =>
            !e.IsDeleted
            && e.TenantId == CurrentTenantId);
    }

    private void ApplyTenantOwnedFilter<TEntity>(ModelBuilder modelBuilder)
        where TEntity : TenantOwnedEntity
    {
        modelBuilder.Entity<TEntity>().HasQueryFilter(e =>
            !e.IsDeleted
            && e.TenantId == CurrentTenantId
            && e.CompanyId == CurrentCompanyId);
    }
}
