using System.Globalization;
using Accountrack.Application.Abstractions.Context;
using Accountrack.Application.Abstractions.Messaging;
using Accountrack.Modules.Contracts.Company;
using Accountrack.Modules.Contracts.MasterData;
using Accountrack.Sales.Application.Abstractions;
using Accountrack.Sales.Domain;
using Accountrack.SharedKernel.Pdf;
using Accountrack.SharedKernel.Results;

namespace Accountrack.Sales.Application.Features;

internal static class SalesPdfFormat
{
    private static readonly CultureInfo Id = new("id-ID");

    public static string Money(decimal value, string currency) => $"{currency} {value.ToString("N0", Id)}";
    public static string Qty(decimal value) => value.ToString("0.####", CultureInfo.InvariantCulture);
    public static string Pct(decimal rate) => (rate * 100m).ToString("0.##", CultureInfo.InvariantCulture) + "%";

    public static PdfParty Seller(CompanyInfo c)
    {
        var lines = new List<string>();
        if (!string.IsNullOrWhiteSpace(c.LegalName) && c.LegalName != c.Name) lines.Add(c.LegalName!);
        if (!string.IsNullOrWhiteSpace(c.TaxId)) lines.Add($"NPWP: {c.TaxId}");
        return new PdfParty(string.IsNullOrWhiteSpace(c.Name) ? c.Code : c.Name, lines);
    }

    public static string Footer(CompanyInfo c) =>
        $"{(string.IsNullOrWhiteSpace(c.Name) ? c.Code : c.Name)} · Generated by Accountrack";
}

// --- Sales invoice PDF ---

public sealed record GetSalesInvoicePdfQuery(Guid Id) : IQuery<PdfDocument>;

public sealed class GetSalesInvoicePdfHandler : IQueryHandler<GetSalesInvoicePdfQuery, PdfDocument>
{
    private readonly ISalesInvoiceRepository _invoices;
    private readonly IMasterDataLookup _lookup;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;

    public GetSalesInvoicePdfHandler(
        ISalesInvoiceRepository invoices, IMasterDataLookup lookup, ICompanyDirectory companies, ITenantContext tenant)
    {
        _invoices = invoices;
        _lookup = lookup;
        _companies = companies;
        _tenant = tenant;
    }

    public async Task<Result<PdfDocument>> Handle(GetSalesInvoicePdfQuery request, CancellationToken ct)
    {
        var invoice = await _invoices.GetByIdAsync(request.Id, ct);
        if (invoice is null)
        {
            return Error.NotFound("SALES.SI_NOT_FOUND", "Sales invoice not found.");
        }

        var company = await _companies.GetAsync(_tenant.CompanyId, ct);
        var names = await _lookup.ResolveNamesAsync(
            invoice.Lines.Select(l => l.ProductId).Append(invoice.CustomerId).Distinct().ToArray(), ct);

        var cur = invoice.Currency;
        var lines = invoice.Lines.Select(l => new PdfLineItem(
            names.GetValueOrDefault(l.ProductId, l.ProductId.ToString()),
            SalesPdfFormat.Qty(l.Quantity),
            SalesPdfFormat.Money(l.UnitPrice, cur),
            SalesPdfFormat.Pct(l.TaxRate),
            SalesPdfFormat.Money(l.LineTotal, cur))).ToList();

        var totals = new List<PdfTotalLine>
        {
            new("Subtotal", SalesPdfFormat.Money(invoice.SubTotal, cur)),
            new("VAT (PPN)", SalesPdfFormat.Money(invoice.TaxTotal, cur)),
            new("Total", SalesPdfFormat.Money(invoice.GrandTotal, cur), Emphasis: true),
        };

        return new PdfDocument(
            "Invoice", invoice.Number,
            company is null ? new PdfParty("Accountrack", Array.Empty<string>()) : SalesPdfFormat.Seller(company),
            "Bill To",
            new PdfParty(names.GetValueOrDefault(invoice.CustomerId, invoice.CustomerId.ToString()), Array.Empty<string>()),
            new[]
            {
                new PdfField("Invoice date", invoice.InvoiceDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
                new PdfField("Due date", invoice.DueDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
            },
            lines, totals, invoice.Notes,
            company is null ? null : SalesPdfFormat.Footer(company));
    }
}

// --- Quotation PDF (rendered from the sales order) ---

public sealed record GetQuotationPdfQuery(Guid SalesOrderId) : IQuery<PdfDocument>;

public sealed class GetQuotationPdfHandler : IQueryHandler<GetQuotationPdfQuery, PdfDocument>
{
    private readonly ISalesOrderRepository _orders;
    private readonly IMasterDataLookup _lookup;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;

    public GetQuotationPdfHandler(
        ISalesOrderRepository orders, IMasterDataLookup lookup, ICompanyDirectory companies, ITenantContext tenant)
    {
        _orders = orders;
        _lookup = lookup;
        _companies = companies;
        _tenant = tenant;
    }

    public async Task<Result<PdfDocument>> Handle(GetQuotationPdfQuery request, CancellationToken ct)
    {
        var order = await _orders.GetByIdAsync(request.SalesOrderId, ct);
        if (order is null)
        {
            return SalesErrors.NotFound;
        }

        var company = await _companies.GetAsync(_tenant.CompanyId, ct);
        var names = await _lookup.ResolveNamesAsync(
            order.Lines.Select(l => l.ProductId).Append(order.CustomerId).Distinct().ToArray(), ct);

        var cur = order.Currency;
        var lines = order.Lines.Select(l => new PdfLineItem(
            names.GetValueOrDefault(l.ProductId, l.ProductId.ToString()),
            SalesPdfFormat.Qty(l.Quantity),
            SalesPdfFormat.Money(l.UnitPrice, cur),
            SalesPdfFormat.Pct(l.TaxRate),
            SalesPdfFormat.Money(l.LineTotal, cur))).ToList();

        var totals = new List<PdfTotalLine>
        {
            new("Subtotal", SalesPdfFormat.Money(order.SubTotal, cur)),
            new("VAT (PPN)", SalesPdfFormat.Money(order.TaxTotal, cur)),
            new("Total", SalesPdfFormat.Money(order.GrandTotal, cur), Emphasis: true),
        };

        return new PdfDocument(
            "Quotation", order.Number,
            company is null ? new PdfParty("Accountrack", Array.Empty<string>()) : SalesPdfFormat.Seller(company),
            "Quote To",
            new PdfParty(names.GetValueOrDefault(order.CustomerId, order.CustomerId.ToString()), Array.Empty<string>()),
            new[]
            {
                new PdfField("Order date", order.OrderDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
                new PdfField("Valid until", order.OrderDate.AddDays(30).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
            },
            lines, totals, order.Notes,
            company is null ? null : SalesPdfFormat.Footer(company));
    }
}
