using System.Globalization;
using Accountrack.Application.Abstractions.Context;
using Accountrack.Application.Abstractions.Messaging;
using Accountrack.Modules.Contracts.Company;
using Accountrack.SharedKernel.Pdf;
using Accountrack.SharedKernel.Results;
using MediatR;

namespace Accountrack.Accounting.Application.Features;

internal static class ReportPdf
{
    private static readonly CultureInfo Id = new("id-ID");

    public static string Amt(decimal v) => v.ToString("N0", Id);
    public static string? AmtOrBlank(decimal v) => v == 0 ? null : v.ToString("N0", Id);

    public static string Period(DateOnly? from, DateOnly? to)
    {
        static string D(DateOnly d) => d.ToString("d MMM yyyy", CultureInfo.InvariantCulture);
        return (from, to) switch
        {
            (null, null) => "All dates",
            (null, { } t) => $"Up to {D(t)}",
            ({ } f, null) => $"From {D(f)}",
            ({ } f, { } t) => $"{D(f)} – {D(t)}",
        };
    }

    public static async Task<(PdfParty Company, string? Footer)> CompanyAsync(
        ICompanyDirectory companies, ITenantContext tenant, CancellationToken ct)
    {
        var c = await companies.GetAsync(tenant.CompanyId, ct);
        var name = c is null || string.IsNullOrWhiteSpace(c.Name) ? "Accountrack" : c.Name;
        var lines = new List<string>();
        if (c is not null && !string.IsNullOrWhiteSpace(c.TaxId)) lines.Add($"NPWP: {c.TaxId}");
        return (new PdfParty(name, lines), $"{name} · Generated by Accountrack · Amounts in {c?.FunctionalCurrency ?? "IDR"}");
    }
}

// ---- Trial Balance ----
public sealed record GetTrialBalancePdfQuery(DateOnly? FromDate, DateOnly? ToDate) : IQuery<PdfReport>;

public sealed class GetTrialBalancePdfHandler : IQueryHandler<GetTrialBalancePdfQuery, PdfReport>
{
    private readonly ISender _sender;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;
    public GetTrialBalancePdfHandler(ISender sender, ICompanyDirectory companies, ITenantContext tenant)
    { _sender = sender; _companies = companies; _tenant = tenant; }

    public async Task<Result<PdfReport>> Handle(GetTrialBalancePdfQuery request, CancellationToken ct)
    {
        var report = await _sender.Send(new GetTrialBalanceQuery(request.FromDate, request.ToDate), ct);
        if (report.IsFailure) return report.Error;
        var tb = report.Value;
        var (company, footer) = await ReportPdf.CompanyAsync(_companies, _tenant, ct);

        var rows = tb.Lines.Select(l => new PdfReportRow(
            new[] { $"{l.AccountCode}  {l.AccountName}", ReportPdf.AmtOrBlank(l.Debit), ReportPdf.AmtOrBlank(l.Credit) })).ToList();
        rows.Add(new PdfReportRow(new[] { "Total", ReportPdf.Amt(tb.TotalDebit), ReportPdf.Amt(tb.TotalCredit) }, PdfRowStyle.GrandTotal));

        return new PdfReport("Trial Balance", ReportPdf.Period(tb.FromDate, tb.ToDate), company,
            new[] { "Account", "Debit", "Credit" }, rows, footer);
    }
}

// ---- Profit & Loss ----
public sealed record GetProfitAndLossPdfQuery(DateOnly? FromDate, DateOnly? ToDate) : IQuery<PdfReport>;

public sealed class GetProfitAndLossPdfHandler : IQueryHandler<GetProfitAndLossPdfQuery, PdfReport>
{
    private readonly ISender _sender;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;
    public GetProfitAndLossPdfHandler(ISender sender, ICompanyDirectory companies, ITenantContext tenant)
    { _sender = sender; _companies = companies; _tenant = tenant; }

    public async Task<Result<PdfReport>> Handle(GetProfitAndLossPdfQuery request, CancellationToken ct)
    {
        var report = await _sender.Send(new GetProfitAndLossQuery(request.FromDate, request.ToDate), ct);
        if (report.IsFailure) return report.Error;
        var pl = report.Value;
        var (company, footer) = await ReportPdf.CompanyAsync(_companies, _tenant, ct);

        var rows = new List<PdfReportRow> { new(new[] { "Revenue" }, PdfRowStyle.SectionHeader) };
        rows.AddRange(pl.Revenue.Select(l => new PdfReportRow(new[] { $"    {l.AccountName}", ReportPdf.Amt(l.Amount) })));
        rows.Add(new PdfReportRow(new[] { "Total revenue", ReportPdf.Amt(pl.TotalRevenue) }, PdfRowStyle.Subtotal));
        rows.Add(new PdfReportRow(new[] { "Expenses" }, PdfRowStyle.SectionHeader));
        rows.AddRange(pl.Expenses.Select(l => new PdfReportRow(new[] { $"    {l.AccountName}", ReportPdf.Amt(l.Amount) })));
        rows.Add(new PdfReportRow(new[] { "Total expenses", ReportPdf.Amt(pl.TotalExpenses) }, PdfRowStyle.Subtotal));
        rows.Add(new PdfReportRow(new[] { pl.NetProfit >= 0 ? "Net profit" : "Net loss", ReportPdf.Amt(pl.NetProfit) }, PdfRowStyle.GrandTotal));

        return new PdfReport("Profit & Loss", ReportPdf.Period(pl.FromDate, pl.ToDate), company,
            new[] { "Account", "Amount" }, rows, footer);
    }
}

// ---- Balance Sheet ----
public sealed record GetBalanceSheetPdfQuery(DateOnly AsOfDate) : IQuery<PdfReport>;

public sealed class GetBalanceSheetPdfHandler : IQueryHandler<GetBalanceSheetPdfQuery, PdfReport>
{
    private readonly ISender _sender;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;
    public GetBalanceSheetPdfHandler(ISender sender, ICompanyDirectory companies, ITenantContext tenant)
    { _sender = sender; _companies = companies; _tenant = tenant; }

    public async Task<Result<PdfReport>> Handle(GetBalanceSheetPdfQuery request, CancellationToken ct)
    {
        var report = await _sender.Send(new GetBalanceSheetQuery(request.AsOfDate), ct);
        if (report.IsFailure) return report.Error;
        var bs = report.Value;
        var (company, footer) = await ReportPdf.CompanyAsync(_companies, _tenant, ct);

        var rows = new List<PdfReportRow> { new(new[] { "Assets" }, PdfRowStyle.SectionHeader) };
        rows.AddRange(bs.Assets.Select(l => new PdfReportRow(new[] { $"    {l.AccountName}", ReportPdf.Amt(l.Amount) })));
        rows.Add(new PdfReportRow(new[] { "Total assets", ReportPdf.Amt(bs.TotalAssets) }, PdfRowStyle.Subtotal));
        rows.Add(new PdfReportRow(new[] { "Liabilities" }, PdfRowStyle.SectionHeader));
        rows.AddRange(bs.Liabilities.Select(l => new PdfReportRow(new[] { $"    {l.AccountName}", ReportPdf.Amt(l.Amount) })));
        rows.Add(new PdfReportRow(new[] { "Total liabilities", ReportPdf.Amt(bs.TotalLiabilities) }, PdfRowStyle.Subtotal));
        rows.Add(new PdfReportRow(new[] { "Equity" }, PdfRowStyle.SectionHeader));
        rows.AddRange(bs.Equity.Select(l => new PdfReportRow(new[] { $"    {l.AccountName}", ReportPdf.Amt(l.Amount) })));
        rows.Add(new PdfReportRow(new[] { "    Current earnings", ReportPdf.Amt(bs.CurrentEarnings) }));
        rows.Add(new PdfReportRow(new[] { "Total equity", ReportPdf.Amt(bs.TotalEquity) }, PdfRowStyle.Subtotal));
        rows.Add(new PdfReportRow(new[] { "Total liabilities & equity", ReportPdf.Amt(bs.TotalLiabilitiesAndEquity) }, PdfRowStyle.GrandTotal));

        return new PdfReport("Balance Sheet", $"As of {bs.AsOfDate.ToString("d MMM yyyy", CultureInfo.InvariantCulture)}",
            company, new[] { "Account", "Amount" }, rows, footer);
    }
}

// ---- VAT (PPN) ----
public sealed record GetVatReportPdfQuery(DateOnly? FromDate, DateOnly? ToDate) : IQuery<PdfReport>;

public sealed class GetVatReportPdfHandler : IQueryHandler<GetVatReportPdfQuery, PdfReport>
{
    private readonly ISender _sender;
    private readonly ICompanyDirectory _companies;
    private readonly ITenantContext _tenant;
    public GetVatReportPdfHandler(ISender sender, ICompanyDirectory companies, ITenantContext tenant)
    { _sender = sender; _companies = companies; _tenant = tenant; }

    public async Task<Result<PdfReport>> Handle(GetVatReportPdfQuery request, CancellationToken ct)
    {
        var report = await _sender.Send(new GetVatReportQuery(request.FromDate, request.ToDate), ct);
        if (report.IsFailure) return report.Error;
        var v = report.Value;
        var (company, footer) = await ReportPdf.CompanyAsync(_companies, _tenant, ct);

        var rows = new List<PdfReportRow>
        {
            new(new[] { $"VAT Output (PPN Keluaran) · {v.OutputAccountCode}", ReportPdf.Amt(v.OutputTax) }),
            new(new[] { $"VAT Input (PPN Masukan) · {v.InputAccountCode}", ReportPdf.Amt(v.InputTax) }),
            new(new[] { v.NetVatPayable >= 0 ? "VAT payable" : "VAT credit carried forward", ReportPdf.Amt(v.NetVatPayable) }, PdfRowStyle.GrandTotal),
        };

        return new PdfReport("VAT (PPN) Report", ReportPdf.Period(v.FromDate, v.ToDate), company,
            new[] { "Description", "Amount" }, rows, footer);
    }
}
